create build
SkywalkingTest/collector-integration-testtool pull request #3
Opened 2018-04-12 15:59 UTC by wengangJi

The script is started with a container project for the main project and test project based on the github account of the fork and is used for project testing. The boot parameter provides the global configuration of yaml through the docker project.
To do this, execute the build.sh file, enter the fork user name according to the prompt, and then start executing and starting the project.
The output result is expected to start the docker container for the main project and test project, and start the corresponding database service container according to the environment variable.
After startup, you can access the UI page at http://localhost:8080.

2018-04-13 16:19 UTC, peng-yongsheng requested changes

2018-04-13 16:19 UTC, peng-yongsheng commented on docker-compose-es.yaml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
What's this? database docker image definition must in the docker project.

2018-04-13 16:19 UTC, peng-yongsheng commented on docker-compose-h2.yaml
> +  skywalking-webappService:
Did not need web project for auto test.

2018-04-13 16:19 UTC, peng-yongsheng commented on docker-compose.yaml
> +version: '3'
What's the usage about this file? Same as `docker-compose-es.yaml`.

2018-04-14 01:49 UTC, wengangJi commented on docker-compose.yaml
> +version: '3'
This is a legacy file that needs to be cleared. I'll delete it.

2018-04-14 01:52 UTC, wengangJi commented on docker-compose-h2.yaml
> +  skywalking-webappService:
I will be delete it.

2018-04-14 02:08 UTC, wengangJi commented on docker-compose-es.yaml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
Docker compose have involved in the configuration file path to the mount, and according to the environment variables to pursue to the configuration file path, so currently only in the main project. If you're going to be in docker engineering, I need to rebuild implementation.

2018-04-15 15:05 UTC, merged